---
development:
  cloud_name: ENV["cdn_cloud_name"]
  api_key: ENV["cdn_api_key"]
  api_secret: ENV["cdn_api_secret"]
  enhance_image_tag: true
  static_image_support: false
production:
  cloud_name: ENV["cdn_cloud_name"]
  api_key: ENV["cdn_api_key"]
  api_secret: ENV["cdn_api_secret"]
  enhance_image_tag: true
  static_image_support: true
test:
  cloud_name: ENV["cdn_cloud_name"]
  api_key: ENV["cdn_api_key"]
  api_secret: ENV["cdn_api_secret"]
  enhance_image_tag: true
  static_image_support: false
