# Postgresql

default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: ohmyfees_development

test:
  <<: *default
  database: ohmyfees_test

production:
  <<: *default
  database: ohmyfess_production
